export const SITE_VERSION = "1.4.2";
export const PLAYER_NAME = "ketchupandmayo";
export const CURRENT_RUN_PROGRESS = 99.9;
export const NEXT_HARDEST_PROGRESS = 10.43;

export const PROFILE_API = "/api/profile";
export const PROFILE_URL = "https://gdbrowser.com/u/ketchupandmayo";
export const TIKTOK_URL = "https://www.tiktok.com/@nahbro003";

export const FALLBACK_PROFILE = {
  username: "ketchupandmayo",
  playerID: 230485931,
  accountID: 25726691,
  rank: 2395046,
  stars: 583,
  moons: 40,
  diamonds: 1222,
  coins: 73,
  userCoins: 36,
  demons: 31,
  cp: 0,
  icon: 1,
  ship: 17,
  ball: 42,
  ufo: 1,
  wave: 1,
  robot: 1,
  spider: 2,
  swing: 32,
  jetpack: 1,
  col1: 12,
  col2: 12,
  colG: 0,
  glow: false,
  classicDemonsCompleted: {
    easy: 12,
    medium: 4,
    hard: 5,
    insane: 2,
    extreme: 3,
  },
};

export const ICON_FORMS = [
  { form: "cube", field: "icon", name: "CUBE", index: "01" },
  { form: "ship", field: "ship", name: "SHIP", index: "02" },
  { form: "ball", field: "ball", name: "BALL", index: "03" },
  { form: "ufo", field: "ufo", name: "UFO", index: "04" },
  { form: "wave", field: "wave", name: "WAVE", index: "05" },
  { form: "robot", field: "robot", name: "ROBOT", index: "06" },
  { form: "spider", field: "spider", name: "SPIDER", index: "07" },
  { form: "swing", field: "swing", name: "SWING", index: "08" },
  { form: "jetpack", field: "jetpack", name: "JETPACK", index: "09" },
];

export const LEVELS = [
  {
    id: "run",
    kicker: "01 / CURRENT RUN",
    kickerStatus: `NEW BEST • ${CURRENT_RUN_PROGRESS.toFixed(2)}%`,
    eyebrow: "Now grinding",
    title: ["EON"],
    levelId: 101478916,
    demonlist: "global",
    progress: CURRENT_RUN_PROGRESS,
    decimals: 2,
    meterLabel: "THE LAST 0.10%",
    layoutClass: "",
    sectionClass: "",
    quote: {
      before: "Смерть на",
      emphasis: "трипл-спайке.",
      after: "До финиша —",
      strong: "всего 0.10%.",
    },
  },
  {
    id: "zodiac",
    kicker: "02 / NEXT HARDEST",
    kickerStatus: `NEW BEST • ${NEXT_HARDEST_PROGRESS}%`,
    eyebrow: "Next hardest target",
    title: ["ZODIAC"],
    levelId: 52374843,
    demonlist: "global",
    progress: NEXT_HARDEST_PROGRESS,
    decimals: 2,
    meterLabel: "89.57% TO GO",
    layoutClass: "zodiac-run-layout",
    sectionClass: "zodiac-run",
    quoteClass: "zodiac-quote",
    quote: {
      before: "10.43%",
      emphasis: "— только начало.",
      after: "Следующая вершина —",
      strong: "ZODIAC.",
    },
  },
  {
    id: "hardest",
    kicker: "03 / HARDEST",
    kickerStatus: "COMPLETED • 100%",
    eyebrow: "Hardest completed",
    title: ["BLOOD", "BATH"],
    levelId: 10565740,
    demonlist: "global",
    progress: 100,
    decimals: 0,
    meterLabel: "LEVEL CLEARED",
    layoutClass: "bloodbath-run-layout",
    sectionClass: "completed-run",
    quoteClass: "bloodbath-quote",
    quote: {
      before: "Один хардест уже",
      emphasis: "позади.",
      after: "Следующая цель —",
      strong: "EON.",
    },
  },
  {
    id: "acu",
    kicker: "04 / COMPLETED EXTREME DEMON",
    kickerStatus: "COMPLETED • 100%",
    eyebrow: "Extreme Demon completed",
    title: ["ACU"],
    levelId: 61079355,
    demonlist: "global",
    progress: 100,
    decimals: 0,
    meterLabel: "LEVEL CLEARED",
    layoutClass: "acu-run-layout",
    sectionClass: "completed-run acu-run",
    quoteClass: "acu-quote",
    quote: {
      before: "Extreme Demon",
      emphasis: "пройден.",
      after: "ACU —",
      strong: "100%.",
    },
  },
  {
    id: "cataclysm",
    kicker: "05 / COMPLETED EXTREME DEMON",
    kickerStatus: "COMPLETED • 100%",
    eyebrow: "Extreme Demon completed",
    title: ["CATACLYSM"],
    levelId: 3979721,
    demonlist: "global",
    progress: 100,
    decimals: 0,
    meterLabel: "LEVEL CLEARED",
    layoutClass: "cataclysm-run-layout",
    sectionClass: "completed-run cataclysm-run",
    quoteClass: "cataclysm-quote",
    quote: {
      before: "Extreme Demon",
      emphasis: "пройден.",
      after: "CATACLYSM —",
      strong: "100%.",
    },
  },
  {
    id: "denouement",
    kicker: "06 / COMPLETED INSANE DEMON",
    kickerStatus: "COMPLETED • 100%",
    eyebrow: "Insane Demon completed",
    title: ["DENOUEMENT"],
    levelId: 60619762,
    demonlist: "unsupported",
    progress: 100,
    decimals: 0,
    meterLabel: "LEVEL CLEARED",
    layoutClass: "denouement-run-layout",
    sectionClass: "completed-run denouement-run",
    quoteClass: "denouement-quote",
    quote: {
      before: "Insane Demon",
      emphasis: "пройден.",
      after: "DENOUEMENT —",
      strong: "100%.",
    },
  },
];

export function buildPreviewIconUrl(profile, form, field) {
  const query = new URLSearchParams({
    form,
    icon: String(profile[field] ?? 1),
    col1: String(profile.col1 ?? 12),
    col2: String(profile.col2 ?? 12),
    glow: String(Boolean(profile.glow)),
  });

  return `https://gdbrowser.com/icon/icon?${query}`;
}
